@extends('layouts.app')

@section('title', 'Dashboard — LPJU & Rambu')
@section('page-title', 'Dashboard operasional')

@section('content')
@include('components.asset-marker')
<div x-data="{ ready: false }" x-init="setTimeout(() => ready = true, 120)" x-show="ready" x-transition.opacity>
    <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div><p class="text-sm text-slate-600">Ringkasan pemantauan hari ini</p><h2 class="mt-1 text-2xl font-semibold tracking-tight text-navy-900 sm:text-3xl">Selamat bekerja, <span x-text="$store.auth.user?.name || 'Petugas'">Petugas</span></h2></div>
        <div class="flex flex-wrap items-center gap-2 self-start sm:self-auto"><a href="{{ route('assets.map') }}" class="inline-flex min-h-10 items-center gap-2 rounded-lg bg-navy-900 px-4 text-sm font-semibold text-white transition-colors hover:bg-navy-800"><svg class="h-4 w-4" aria-hidden="true" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Zm6-3v15m6-12v15" /></svg> Buka peta aset</a><div class="inline-flex items-center gap-2 rounded-full border border-border bg-white px-3 py-2 text-xs font-medium text-slate-600"><span class="h-2 w-2 rounded-full bg-teal-500"></span> Sistem aktif <span class="text-slate-300">•</span> {{ now()->format('d M Y') }}</div></div>
    </div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach ([['label' => 'Total LPJU', 'value' => '1.248', 'meta' => '+8 aset bulan ini', 'color' => 'teal'], ['label' => 'Total Rambu', 'value' => '836', 'meta' => '+12 aset bulan ini', 'color' => 'yellow'], ['label' => 'Aduan masuk', 'value' => '24', 'meta' => '7 perlu ditindak', 'color' => 'orange'], ['label' => 'Aduan selesai', 'value' => '91%', 'meta' => '+4% dibanding bulan lalu', 'color' => 'blue']] as $stat)
            <article class="rounded-2xl border border-border bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><p class="text-sm font-medium text-slate-600">{{ $stat['label'] }}</p><span class="h-3 w-3 rounded-full bg-{{ $stat['color'] }}-400"></span></div><p class="mt-4 text-3xl font-semibold tracking-tight text-navy-900">{{ $stat['value'] }}</p><p class="mt-2 text-xs text-slate-500">{{ $stat['meta'] }}</p></article>
        @endforeach
    </div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,0.55fr)]">
        <section class="overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div class="flex items-center justify-between border-b border-border px-5 py-4"><div><h3 class="font-semibold text-navy-900">Aduan terbaru</h3><p class="mt-1 text-xs text-slate-500">Prioritas penanganan lapangan</p></div><button class="min-h-10 rounded-lg px-3 text-sm font-semibold text-teal-700 hover:bg-teal-50">Lihat semua</button></div><div class="overflow-x-auto"><table class="w-full min-w-[600px] text-left text-sm"><caption class="sr-only">Daftar aduan terbaru</caption><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3 font-semibold">Aset</th><th class="px-5 py-3 font-semibold">Wilayah</th><th class="px-5 py-3 font-semibold">Tanggal</th><th class="px-5 py-3 font-semibold">Status</th></tr></thead><tbody class="divide-y divide-border"><tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-navy-900">LPJU-KBM-0001</td><td class="px-5 py-4 text-slate-600">Kec. Kebumen</td><td class="px-5 py-4 text-slate-600">18 Sep 2026</td><td class="px-5 py-4"><span class="inline-flex rounded-full bg-yellow-100 px-2.5 py-1 text-xs font-medium text-yellow-800">Diproses</span></td></tr><tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-navy-900">RAMBU-KBM-0017</td><td class="px-5 py-4 text-slate-600">Kec. Gombong</td><td class="px-5 py-4 text-slate-600">17 Sep 2026</td><td class="px-5 py-4"><span class="inline-flex rounded-full bg-teal-100 px-2.5 py-1 text-xs font-medium text-teal-800">Selesai</span></td></tr><tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-navy-900">LPJU-KBM-0042</td><td class="px-5 py-4 text-slate-600">Kec. Prembun</td><td class="px-5 py-4 text-slate-600">16 Sep 2026</td><td class="px-5 py-4"><span class="inline-flex rounded-full bg-red-100 px-2.5 py-1 text-xs font-medium text-red-800">Baru</span></td></tr></tbody></table></div></section>
        <section x-data="dashboardMapPreview()" x-init="init()" class="relative overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div class="flex items-start justify-between border-b border-border px-5 py-4"><div><p class="text-xs font-semibold uppercase tracking-widest text-teal-600">PETA ASET</p><h3 class="mt-1 text-xl font-semibold text-navy-900">Peta aset Kebumen</h3><p class="mt-1 text-sm text-slate-600">Pantau lokasi LPJU dan Rambu secara langsung.</p></div><a href="{{ route('assets.map') }}" class="inline-flex min-h-10 items-center rounded-lg bg-navy-900 px-3 text-xs font-semibold text-white hover:bg-navy-800">Buka peta lengkap</a></div><div class="relative h-64"><div id="dashboard-asset-map" class="absolute inset-0"></div><div class="pointer-events-none absolute bottom-3 left-3 z-[500] rounded-lg bg-white/95 px-3 py-2 text-xs text-slate-700 shadow"><span class="mr-3"><i class="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-teal-500"></i>LPJU <strong x-text="counts.lpju">0</strong></span><span><i class="mr-1 inline-block h-2.5 w-2.5 rounded-full bg-amber-500"></i>Rambu <strong x-text="counts.rambu">0</strong></span></div><div x-show="loading" class="absolute inset-0 z-[600] flex items-center justify-center bg-white/70 text-sm text-slate-600">Memuat peta...</div><div x-show="error" class="absolute inset-x-4 top-4 z-[600] rounded-lg bg-red-50 px-3 py-2 text-xs text-red-700" x-text="error"></div></div></section>
    </div>
</div>
<script>
function dashboardMapPreview() {
    return { map: null, loading: true, error: '', counts: { lpju: 0, rambu: 0 }, init() { if (!window.Leaflet || this.map) return; this.map = window.Leaflet.map('dashboard-asset-map', { center: [-7.6786, 109.6565], zoom: 10, minZoom: 9, maxZoom: 14, scrollWheelZoom: false, zoomControl: false }); window.Leaflet.control.zoom({ position: 'bottomright' }).addTo(this.map); window.Leaflet.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(this.map); Promise.all([window.axios.get('/api/lpju'), window.axios.get('/api/rambu')]).then(([lpju, rambu]) => { const items = [{ data: lpju.data || [], type: 'lpju' }, { data: rambu.data || [], type: 'rambu' }]; items.forEach(({ data, type }) => { this.counts[type] = data.length; data.forEach((asset) => { const lat = Number.parseFloat(asset.latitude), lng = Number.parseFloat(asset.longitude); if (!Number.isFinite(lat) || !Number.isFinite(lng)) return; const item = { ...asset, type, kode: `${type === 'lpju' ? 'LPJU' : 'RAMBU'}-${String(asset.id).padStart(4, '0')}` }; const marker = window.Leaflet.marker([lat, lng], { icon: window.assetMarkerIcon(item), title: item.kode }); marker.bindTooltip(item.kode, { direction: 'top' }).bindPopup(`<strong>${item.kode}</strong><br>${item.alamat || '-'}` ).addTo(this.map); }); }); }).catch((e) => { this.error = 'Data peta belum dapat dimuat.'; console.warn('[dashboard-map]', e); }).finally(() => { this.loading = false; setTimeout(() => this.map.invalidateSize(), 100); }); setTimeout(() => this.map.invalidateSize(), 100); } };
}
</script>
@endsection
