@extends('layouts.app')
@section('title', 'Data LPJU')
@section('page-title', 'Data LPJU')
@section('content')
<div x-data="lpjuIndex()" x-init="init()" x-cloak>
    <div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm text-slate-600">Inventaris lampu penerangan jalan umum</p><h2 class="mt-1 text-2xl font-semibold tracking-tight text-navy-900 sm:text-3xl">Data LPJU</h2></div><a href="{{ route('assets.lpju.create') }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-navy-900 px-4 text-sm font-semibold text-white hover:bg-navy-800">+ Tambah LPJU</a></div>
    <div x-show="notice" class="mb-4 rounded-xl border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-800" x-text="notice"></div>
    <section class="rounded-2xl border border-border bg-white p-4 shadow-sm"><div class="grid gap-3 md:grid-cols-3"><div class="md:col-span-1"><label for="search" class="field-label">Cari alamat, kecamatan, atau kode</label><input id="search" x-model="search" type="search" class="field-input" placeholder="LPJU-0001 atau nama jalan"></div><div><label for="status-filter" class="field-label">Status</label><select id="status-filter" x-model="filters.status" class="field-input"><option value="">Semua status</option><option value="baik">Baik</option><option value="rusak">Rusak</option><option value="perbaikan">Perbaikan</option></select></div><div><label for="year-filter" class="field-label">Tahun anggaran</label><select id="year-filter" x-model="filters.year" class="field-input"><option value="">Semua tahun</option><template x-for="year in years" :key="year"><option :value="String(year)" x-text="year"></option></template></select></div></div></section>
    <div x-show="error" role="alert" class="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><span x-text="error"></span> <button @click="load()" class="font-semibold underline">Coba lagi</button></div>
    <section class="mt-5 overflow-hidden rounded-2xl border border-border bg-white shadow-sm"><div class="flex items-center justify-between border-b border-border px-5 py-4"><div><h3 class="font-semibold text-navy-900">Daftar aset</h3><p class="mt-1 text-xs text-slate-500" x-text="`${filtered.length} aset ditampilkan`"></p></div><span x-show="loading" class="text-xs text-slate-500">Memuat...</span></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Kode</th><th class="px-5 py-3">Lokasi</th><th class="px-5 py-3">Kecamatan</th><th class="px-5 py-3">Tahun</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-border"><template x-for="item in filtered" :key="item.id"><tr class="hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-navy-900" x-text="code(item)"></td><td class="max-w-xs px-5 py-4 text-slate-600" x-text="item.alamat || '-' "></td><td class="px-5 py-4 text-slate-600" x-text="item.desa?.kecamatan?.kecamatan || item.desa?.kec_dtks || '-' "></td><td class="px-5 py-4 text-slate-600" x-text="item.tahun_anggaran || '-' "></td><td class="px-5 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-medium" :class="statusClass(item.status)" x-text="item.status || '-' "></span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a :href="`/assets/lpju/${item.id}`" class="action-link">Detail</a><a :href="`/assets/lpju/${item.id}/edit`" class="action-link">Edit</a><button x-show="$store.auth.role === 'admin'" @click="remove(item)" class="action-link text-red-600">Hapus</button></div></td></tr></template></tbody></table></div><div x-show="!loading && !error && filtered.length === 0" class="px-5 py-16 text-center text-sm text-slate-500">Tidak ada data LPJU yang sesuai.</div></section>
</div>
<script>
function lpjuIndex() { return { assets: [], loading: true, error: '', notice: new URLSearchParams(location.search).get('success') === 'created' ? 'LPJU berhasil ditambahkan.' : new URLSearchParams(location.search).get('success') === 'updated' ? 'LPJU berhasil diperbarui.' : '', search: '', filters: { status: '', year: '' }, get years() { return [...new Set(this.assets.map(x => x.tahun_anggaran).filter(Boolean))].sort((a,b) => b-a); }, get filtered() { const q=this.search.toLowerCase().trim(); return this.assets.filter(x => (!q || [this.code(x),x.alamat,x.desa?.kecamatan?.kecamatan,x.desa?.kec_dtks].filter(Boolean).join(' ').toLowerCase().includes(q)) && (!this.filters.status || x.status === this.filters.status) && (!this.filters.year || String(x.tahun_anggaran) === this.filters.year)); }, async init(){ await this.load(); }, async load(){ this.loading=true; this.error=''; try { const r=await window.axios.get('/api/lpju'); this.assets=Array.isArray(r.data)?r.data: r.data?.data || []; } catch(e){ this.error=e.response?.data?.message || 'Gagal memuat data LPJU.'; } finally { this.loading=false; } }, code(x){return `LPJU-${String(x.id).padStart(4,'0')}`;}, statusClass(s){return s==='baik'?'bg-teal-100 text-teal-800':s==='rusak'?'bg-red-100 text-red-800':'bg-yellow-100 text-yellow-800';}, async remove(item){if(!confirm(`Hapus ${this.code(item)}?`))return; try{await window.axios.delete(`/api/lpju/${item.id}`);this.notice='LPJU berhasil dihapus.';await this.load();}catch(e){this.error=e.response?.data?.message||'Gagal menghapus LPJU.';}}};
}
</script>
@endsection
