<?php
namespace Tests\Feature;
use App\Models\{Desa,Histori,Kecamatan,Lpju,Rambu,SumberDana,User};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Schema\Blueprint;
use Tests\TestCase;
class AssetSecurityTest extends TestCase {
 use RefreshDatabase;
 protected function setUp(): void { parent::setUp(); $this->refs(); }
 public function test_login_rate_limit(): void { Http::fake(['google.com/recaptcha/api/siteverify'=>Http::response(['success'=>true])]); User::factory()->create(['email'=>'rate@example.test']); for($i=0;$i<5;$i++) $this->postJson('/api/login',['email'=>'rate@example.test','password'=>'wrong','captcha_token'=>'x']); $this->postJson('/api/login',['email'=>'rate@example.test','password'=>'wrong','captcha_token'=>'x'])->assertStatus(429); }
 public function test_aduan_rate_limit(): void { $a=$this->lpju(); $p=['jenis_aset'=>'lpju','aset_id'=>$a->id,'nama_pelapor'=>'Warga','deskripsi'=>'Rusak']; for($i=0;$i<10;$i++) $this->postJson('/api/aduan',$p+['kontak_pelapor'=>"081$i"]); $this->postJson('/api/aduan',$p)->assertStatus(429); }
 public function test_lpju_operator_admin_matrix_validation_upload(): void { $u=User::factory()->create(['role'=>'operator']); $r=$this->actingAs($u,'sanctum')->post('/api/lpju',$this->payload(['foto'=>UploadedFile::fake()->image('x.jpg')]),['Accept'=>'application/json']); $r->assertCreated(); $id=$r->json('id'); $this->actingAs($u,'sanctum')->putJson("/api/lpju/$id",['status'=>'rusak'])->assertOk(); $this->actingAs($u,'sanctum')->deleteJson("/api/lpju/$id")->assertForbidden(); $this->actingAs($u,'sanctum')->postJson('/api/lpju',$this->payload(['latitude'=>91,'status'=>'bad']))->assertUnprocessable(); $admin=User::factory()->create(['role'=>'admin']); $this->actingAs($admin,'sanctum')->deleteJson("/api/lpju/$id")->assertOk(); }
 public function test_rambu_operator_admin_matrix_validation(): void { $u=User::factory()->create(['role'=>'operator']); $r=$this->actingAs($u,'sanctum')->postJson('/api/rambu',$this->payload(['jenis_rambu'=>'Peringatan'])); $r->assertCreated(); $id=$r->json('id'); $this->actingAs($u,'sanctum')->putJson("/api/rambu/$id",['status'=>'rusak'])->assertOk(); $this->actingAs($u,'sanctum')->deleteJson("/api/rambu/$id")->assertForbidden(); $this->actingAs($u,'sanctum')->postJson('/api/rambu',$this->payload(['jenis_rambu'=>'X','longitude'=>-181,'status'=>'bad']))->assertUnprocessable(); $admin=User::factory()->create(['role'=>'admin']); $this->actingAs($admin,'sanctum')->deleteJson("/api/rambu/$id")->assertOk(); }
 public function test_history_only_on_status_change(): void { $u=User::factory()->create(['role'=>'operator']); $a=$this->lpju(['status'=>'baik']); $this->actingAs($u,'sanctum')->putJson("/api/lpju/{$a->id}",['status'=>'rusak'])->assertOk(); $this->assertDatabaseCount('histori',1); $this->actingAs($u,'sanctum')->putJson("/api/lpju/{$a->id}",['alamat'=>'new'])->assertOk(); $this->assertDatabaseCount('histori',1); }
 public function test_history_failure_rolls_back(): void { Event::listen('eloquent.creating: '.Histori::class,fn()=>throw new \RuntimeException('fail')); $u=User::factory()->create(['role'=>'operator']); $a=$this->lpju(['status'=>'baik']); $this->actingAs($u,'sanctum')->putJson("/api/lpju/{$a->id}",['status'=>'rusak'])->assertStatus(500); $this->assertDatabaseHas('lpju',['id'=>$a->id,'status'=>'baik']); $this->assertDatabaseCount('histori',0); }
 public function test_history_failure_rolls_back_rambu(): void { Event::listen('eloquent.creating: '.Histori::class,fn()=>throw new \RuntimeException('fail')); $u=User::factory()->create(['role'=>'operator']); $a=$this->rambu(['status'=>'baik']); $this->actingAs($u,'sanctum')->putJson("/api/rambu/{$a->id}",['status'=>'rusak'])->assertStatus(500); $this->assertDatabaseHas('rambu',['id'=>$a->id,'status'=>'baik']); $this->assertDatabaseCount('histori',0); }
 public function test_replacing_lpju_photo_deletes_old_photo(): void { Storage::fake('public'); $u=User::factory()->create(['role'=>'operator']); $old=UploadedFile::fake()->image('old.jpg'); $r=$this->actingAs($u,'sanctum')->post('/api/lpju',$this->payload(['foto'=>$old]),['Accept'=>'application/json']); $r->assertCreated(); $oldPath=$r->json('foto'); Storage::disk('public')->assertExists($oldPath); $new=UploadedFile::fake()->image('new.jpg'); $this->actingAs($u,'sanctum')->put("/api/lpju/{$r->json('id')}",['foto'=>$new],['Accept'=>'application/json']); Storage::disk('public')->assertMissing($oldPath); Storage::disk('public')->assertExists(Lpju::find($r->json('id'))->foto); }
 public function test_replacing_rambu_photo_deletes_old_photo(): void { Storage::fake('public'); $u=User::factory()->create(['role'=>'operator']); $r=$this->actingAs($u,'sanctum')->post('/api/rambu',$this->payload(['jenis_rambu'=>'Peringatan','foto'=>UploadedFile::fake()->image('old.jpg')]),['Accept'=>'application/json']); $r->assertCreated(); $oldPath=$r->json('foto'); Storage::disk('public')->assertExists($oldPath); $this->actingAs($u,'sanctum')->put("/api/rambu/{$r->json('id')}",['foto'=>UploadedFile::fake()->image('new.jpg')],['Accept'=>'application/json']); Storage::disk('public')->assertMissing($oldPath); Storage::disk('public')->assertExists(Rambu::find($r->json('id'))->foto); }
 private function payload(array $x=[]): array { return array_merge(['desa_id'=>Desa::first()->id,'sumber_dana_id'=>SumberDana::first()->id,'alamat'=>'Jalan','latitude'=>-6.2,'longitude'=>106.8,'status'=>'baik'],$x); }
 private function rambu(array $x=[]): Rambu { return Rambu::create($this->payload($x)+['jenis_rambu'=>'Peringatan','petugas_id'=>User::factory()->create(['role'=>'operator'])->id]); }
 private function lpju(array $x=[]): Lpju { return Lpju::create($this->payload($x)+['petugas_id'=>User::factory()->create(['role'=>'operator'])->id]); }
 private function refs(): void { if(!Schema::hasTable('kecamatan')) Schema::create('kecamatan',function(Blueprint $t){$t->id();$t->string('kode');$t->string('kecamatan');$t->timestamps();}); if(!Schema::hasTable('desa')) Schema::create('desa',function(Blueprint $t){$t->id();$t->string('kd_kec');$t->string('kd_desa');$t->string('desa');$t->timestamps();}); if(!SumberDana::exists()) SumberDana::create(['nama_sumber'=>'APBD']); if(!Kecamatan::exists()) Kecamatan::create(['kode'=>'01','kecamatan'=>'Test']); if(!Desa::exists()) Desa::create(['kd_kec'=>'01','kd_desa'=>'001','desa'=>'Test']); }
}
