@include('components.location-marker')
@php($editing = $editing ?? false)
<div x-data="rambuForm({{ $editing ? 'true' : 'false' }}, @js($id ?? null))" x-init="init()" x-cloak>
    <div x-show="error" role="alert" class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" x-text="error"></div>
    <div x-show="success" role="status" class="mb-5 rounded-xl border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-800" x-text="success"></div>
    <form @submit.prevent="submit" class="space-y-6" novalidate>
        <section class="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6">
            <h3 class="font-semibold text-navy-900">Informasi rambu</h3>
            <div class="mt-5 grid gap-5 sm:grid-cols-2">
                <div class="relative z-20" @click.outside="closeDesa()">
                    <label for="desa-search" class="field-label">Desa <span class="text-red-500">*</span></label>
                    <input type="hidden" name="desa_id" x-model="form.desa_id">
                    <div class="relative">
                        <input id="desa-search" type="text" x-model="desaSearch" @focus="openDesa = true; activeDesaIndex = filteredDesa.length ? 0 : -1" @keydown="desaKeydown($event)" role="combobox" :aria-expanded="openDesa.toString()" aria-controls="desa-options" aria-autocomplete="list" :aria-activedescendant="activeDesaId" class="field-input pr-20" placeholder="Cari desa..." autocomplete="off">
                        <button type="button" x-show="form.desa_id" @click="clearDesa()" class="desa-clear" aria-label="Hapus pilihan desa">Hapus</button>
                        <button type="button" @click="toggleDesa()" class="desa-toggle" aria-label="Buka pilihan desa" :aria-expanded="openDesa.toString()">⌄</button>
                    </div>
                    <div x-cloak x-show="openDesa" id="desa-options" role="listbox" class="desa-options">
                        <template x-for="(desa, index) in filteredDesa" :key="desa.id">
                            <button type="button" :id="`desa-option-${desa.id}`" role="option" :aria-selected="String(desa.id) === String(form.desa_id)" @mouseenter="activeDesaIndex = index" @click="selectDesa(desa)" :class="activeDesaIndex === index ? 'desa-option--active' : ''" class="desa-option">
                                <span x-text="desaLabel(desa)"></span>
                            </button>
                        </template>
                        <p x-show="filteredDesa.length === 0" class="desa-empty">Desa tidak ditemukan</p>
                    </div>
                    <p x-show="fieldErrors.desa_id" class="field-error" x-text="fieldErrors.desa_id"></p>
                </div>
                <div><label for="sumber_dana_id" class="field-label">Sumber dana <span class="text-red-500">*</span></label><select id="sumber_dana_id" x-model="form.sumber_dana_id" class="field-input" required><option value="">Pilih sumber dana</option><template x-for="source in lookups.sumberDana" :key="source.id"><option :value="String(source.id)" x-text="source.nama_sumber"></option></template></select><p x-show="fieldErrors.sumber_dana_id" class="field-error" x-text="fieldErrors.sumber_dana_id"></p></div>
                <div><label for="jenis_rambu" class="field-label">Jenis rambu <span class="text-red-500">*</span></label><input id="jenis_rambu" x-model="form.jenis_rambu" type="text" maxlength="255" class="field-input" required><p x-show="fieldErrors.jenis_rambu" class="field-error" x-text="fieldErrors.jenis_rambu"></p></div><div class="sm:col-span-2"><label for="alamat" class="field-label">Alamat <span class="text-red-500">*</span></label><input id="alamat" x-model="form.alamat" type="text" maxlength="255" class="field-input" placeholder="Jl. ..." required><p x-show="fieldErrors.alamat" class="field-error" x-text="fieldErrors.alamat"></p></div>
            </div>
        </section>
        <section class="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6">
            <h3 class="font-semibold text-navy-900">Lokasi dan pemasangan</h3>
            <div class="mt-5 grid gap-5 sm:grid-cols-2">
                <div class="sm:col-span-2 rounded-xl border border-border bg-slate-50 p-3"><p class="text-sm font-semibold text-navy-900">Pilih lokasi dari peta</p><p class="mt-1 text-xs text-slate-600">Klik lokasi Rambu pada peta untuk mengisi koordinat.</p><div id="rambu-location-map" class="mt-3 h-64 w-full overflow-hidden rounded-lg bg-[#dbe7e5]"></div><div class="mt-3 flex flex-wrap gap-2"><button type="button" @click="clearLocation" class="min-h-10 rounded-lg border border-border bg-white px-3 text-xs font-semibold text-slate-700">Hapus titik</button><button type="button" @click="useMyLocation" class="min-h-10 rounded-lg border border-border bg-white px-3 text-xs font-semibold text-slate-700">Gunakan lokasi saya</button></div><p x-show="locationError" class="mt-2 text-xs text-red-600" x-text="locationError"></p></div><div><label for="latitude" class="field-label">Latitude <span class="text-red-500">*</span></label><input id="latitude" x-model="form.latitude" type="text" inputmode="decimal" class="field-input" placeholder="-7.6786" required><p x-show="fieldErrors.latitude" class="field-error" x-text="fieldErrors.latitude"></p></div>
                <div><label for="longitude" class="field-label">Longitude <span class="text-red-500">*</span></label><input id="longitude" x-model="form.longitude" type="text" inputmode="decimal" class="field-input" placeholder="109.6565" required><p x-show="fieldErrors.longitude" class="field-error" x-text="fieldErrors.longitude"></p></div>
                <div><label for="tahun_anggaran" class="field-label">Tahun anggaran</label><input id="tahun_anggaran" x-model="form.tahun_anggaran" type="number" min="2000" max="2100" class="field-input" placeholder="2026"></div>
                <div><label for="status" class="field-label">Status</label><select id="status" x-model="form.status" class="field-input"><option value="baik">Baik</option><option value="rusak">Rusak</option><option value="perbaikan">Perbaikan</option></select></div>
                <div><label for="tanggal_diterima" class="field-label">Tanggal diterima</label><input id="tanggal_diterima" x-model="form.tanggal_diterima" type="date" class="field-input"></div>
                <div><label for="tanggal_pasang" class="field-label">Tanggal pasang</label><input id="tanggal_pasang" x-model="form.tanggal_pasang" type="date" class="field-input"></div>
                <div class="sm:col-span-2"><label for="foto" class="field-label">Foto aset <span class="font-normal text-slate-500">(JPG, PNG, WEBP maksimal 2 MB)</span></label><input id="foto" type="file" accept="image/jpeg,image/png,image/webp" @change="form.foto = $event.target.files[0] || null" class="field-input file:mr-3 file:rounded-md file:border-0 file:bg-slate-100 file:px-3 file:py-1 file:text-xs file:font-semibold"><p x-show="currentPhoto" class="mt-2 text-xs text-slate-500">Foto saat ini: <span x-text="currentPhoto"></span></p><p x-show="fieldErrors.foto" class="field-error" x-text="fieldErrors.foto"></p></div>
                <div x-show="editing" class="sm:col-span-2"><label for="keterangan_histori" class="field-label">Keterangan perubahan status</label><input id="keterangan_histori" x-model="form.keterangan_histori" type="text" maxlength="255" class="field-input" placeholder="Opsional, tersimpan pada histori jika status berubah"></div>
            </div>
        </section>
        <div class="flex flex-col-reverse justify-end gap-3 sm:flex-row"><a href="{{ route('assets.rambu.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-lg border border-border px-5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Batal</a><button type="submit" :disabled="saving" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-navy-900 px-5 text-sm font-semibold text-white hover:bg-navy-800 disabled:cursor-not-allowed disabled:opacity-60"><span x-show="saving" class="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"></span><span x-text="saving ? 'Menyimpan...' : (editing ? 'Simpan perubahan' : 'Simpan Rambu')">Simpan Rambu</span></button></div>
    </form>
</div>
<script>
function rambuForm(editing, id) {
    return { editing, id, saving: false, error: '', success: '', currentPhoto: '', locationError: '', map: null, locationMarker: null, desaSearch: '', openDesa: false, activeDesaIndex: -1, lookups: { desa: [], sumberDana: [] }, fieldErrors: {}, form: { desa_id: '', sumber_dana_id: '', jenis_rambu: '', alamat: '', latitude: '', longitude: '', tahun_anggaran: '', tanggal_diterima: '', tanggal_pasang: '', status: 'baik', foto: null, keterangan_histori: '' },
        async init() { if (!this.$store.auth.isAuthenticated || !['admin', 'operator'].includes(this.$store.auth.role)) { window.location.href = '{{ route('login') }}'; return; } try { const requests = [window.axios.get('/api/desa'), window.axios.get('/api/sumber-dana')]; if (this.editing) requests.push(window.axios.get(`/api/rambu/${this.id}`)); const results = await Promise.all(requests); this.lookups.desa = this.normalizeList(results[0]); this.lookups.sumberDana = this.normalizeList(results[1]); if (this.editing) this.fill(this.normalizeItem(results[2])); this.initLocationMap(); } catch (e) { this.error = this.message(e); } },
        normalizeList(response) { const value = response?.data ?? response; return Array.isArray(value) ? value : (Array.isArray(value?.data) ? value.data : []); },
        normalizeItem(response) { const value = response?.data ?? response; return value?.data && !Array.isArray(value.data) ? value.data : value; },
        initLocationMap() { if (this.map || !window.Leaflet) return; const center = [-7.6786, 109.6565]; this.map = window.Leaflet.map('rambu-location-map', { center, zoom: 11, scrollWheelZoom: false, minZoom: 9, maxZoom: 18 }); window.Leaflet.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(this.map); this.map.on('click', (event) => this.setLocation(event.latlng.lat, event.latlng.lng)); const lat = Number.parseFloat(this.form.latitude), lng = Number.parseFloat(this.form.longitude); if (Number.isFinite(lat) && Number.isFinite(lng)) { this.setLocation(lat, lng, false); this.map.setView([lat, lng], 14); } setTimeout(() => this.map.invalidateSize(), 100); },
        setLocation(lat, lng, recenter = true) { if (lat < -90 || lat > 90 || lng < -180 || lng > 180) return; this.form.latitude = lat.toFixed(6); this.form.longitude = lng.toFixed(6); this.locationError = ''; if (this.locationMarker) this.locationMarker.setLatLng([lat, lng]); else { this.locationMarker = window.Leaflet.marker([lat, lng], { icon: window.locationMarkerIcon(), title: 'Lokasi terpilih' }).addTo(this.map); this.locationMarker.bindTooltip('Lokasi terpilih', { direction: 'top', offset: [0, -42] }); } if (recenter) this.map.setView([lat, lng], Math.max(this.map.getZoom(), 13)); },
        clearLocation() { this.form.latitude = ''; this.form.longitude = ''; if (this.locationMarker) { this.locationMarker.remove(); this.locationMarker = null; } },
        get selectedDesa() { return this.lookups.desa.find((desa) => String(desa.id) === String(this.form.desa_id)); },
        get filteredDesa() { const query = this.desaSearch.trim().toLowerCase(); return this.lookups.desa.filter((desa) => this.desaLabel(desa).toLowerCase().includes(query)); },
        get activeDesaId() { const desa = this.filteredDesa[this.activeDesaIndex]; return desa ? `desa-option-${desa.id}` : ''; },
        desaLabel(desa) { return `${desa.desa} — ${desa.kecamatan?.kecamatan || desa.kec_dtks || '-'}`; },
        toggleDesa() { this.openDesa = !this.openDesa; if (this.openDesa) this.activeDesaIndex = this.selectedDesa ? this.filteredDesa.findIndex((desa) => String(desa.id) === String(this.form.desa_id)) : 0; },
        closeDesa() { this.openDesa = false; if (this.selectedDesa) this.desaSearch = this.desaLabel(this.selectedDesa); },
        selectDesa(desa) { this.form.desa_id = String(desa.id); this.desaSearch = this.desaLabel(desa); this.openDesa = false; this.activeDesaIndex = -1; },
        clearDesa() { this.form.desa_id = ''; this.desaSearch = ''; this.openDesa = false; this.activeDesaIndex = -1; },
        desaKeydown(event) { if (!this.openDesa && ['ArrowDown', 'Enter'].includes(event.key)) { this.toggleDesa(); event.preventDefault(); return; } if (event.key === 'Escape') { this.closeDesa(); return; } if (event.key === 'ArrowDown') { this.activeDesaIndex = Math.min(this.activeDesaIndex + 1, this.filteredDesa.length - 1); event.preventDefault(); } if (event.key === 'ArrowUp') { this.activeDesaIndex = Math.max(this.activeDesaIndex - 1, 0); event.preventDefault(); } if (event.key === 'Enter' && this.filteredDesa[this.activeDesaIndex]) { this.selectDesa(this.filteredDesa[this.activeDesaIndex]); event.preventDefault(); } },
        useMyLocation() { if (!navigator.geolocation) { this.locationError = 'Browser tidak mendukung lokasi.'; return; } navigator.geolocation.getCurrentPosition((position) => this.setLocation(position.coords.latitude, position.coords.longitude, true), () => { this.locationError = 'Izin lokasi ditolak atau lokasi tidak tersedia.'; }); },
        fill(item) { this.form = { ...this.form, ...item, desa_id: String(item.desa_id || ''), sumber_dana_id: String(item.sumber_dana_id || ''), foto: null }; this.currentPhoto = item.foto || ''; this.desaSearch = this.selectedDesa ? this.desaLabel(this.selectedDesa) : ''; },
        async submit() { this.saving = true; this.error = ''; this.fieldErrors = {}; if (!this.form.desa_id) { this.fieldErrors.desa_id = 'Desa wajib dipilih.'; this.error = 'Lengkapi field wajib sebelum menyimpan.'; this.saving = false; return; } if (!String(this.form.alamat || '').trim()) { this.fieldErrors.alamat = 'Alamat wajib diisi.'; this.error = 'Lengkapi field wajib sebelum menyimpan.'; this.saving = false; return; } const lat = Number.parseFloat(this.form.latitude), lng = Number.parseFloat(this.form.longitude); if (!Number.isFinite(lat) || lat < -90 || lat > 90) { this.fieldErrors.latitude = 'Latitude wajib berupa angka antara -90 dan 90.'; this.saving = false; return; } if (!Number.isFinite(lng) || lng < -180 || lng > 180) { this.fieldErrors.longitude = 'Longitude wajib berupa angka antara -180 dan 180.'; this.saving = false; return; } const payload = new FormData(); Object.entries(this.form).forEach(([key, value]) => { if (value !== null && value !== '') payload.append(key, value); }); if (this.editing) payload.append('_method', 'PUT'); try { const url = this.editing ? `/api/rambu/${this.id}` : '/api/rambu'; await window.axios.post(url, payload); window.location.href = `/assets/rambu?success=${this.editing ? 'updated' : 'created'}`; } catch (e) { this.fieldErrors = e.response?.data?.errors ? Object.fromEntries(Object.entries(e.response.data.errors).map(([key, value]) => [key, value[0]])) : {}; this.error = this.message(e); } finally { this.saving = false; } },
        message(e) { return e.response?.data?.message || e.message || 'Terjadi kesalahan. Silakan coba lagi.'; }
    };
}
</script>
