@php($editing = $editing ?? false)
<div x-data="rambuForm({{ $editing ? 'true' : 'false' }}, @js($id ?? null))" x-init="init()" x-cloak>
<div x-show="error" role="alert" class="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700" x-text="error"></div>
<form @submit.prevent="submit" class="space-y-6" novalidate>
<section class="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><h3 class="font-semibold text-navy-900">Informasi rambu</h3><div class="mt-5 grid gap-5 sm:grid-cols-2">
<div><label for="jenis_rambu" class="field-label">Jenis rambu <span class="text-red-500">*</span></label><input id="jenis_rambu" x-model="form.jenis_rambu" class="field-input" placeholder="Rambu Peringatan" required><p x-show="fieldErrors.jenis_rambu" class="field-error" x-text="fieldErrors.jenis_rambu"></p></div>
<div><label for="desa_id" class="field-label">Desa <span class="text-red-500">*</span></label><select id="desa_id" x-model="form.desa_id" class="field-input" required><option value="">Pilih desa</option><template x-for="desa in lookups.desa" :key="desa.id"><option :value="String(desa.id)" x-text="`${desa.desa} — ${desa.kecamatan?.kecamatan || desa.kec_dtks || '-'}`"></option></template></select><p x-show="fieldErrors.desa_id" class="field-error" x-text="fieldErrors.desa_id"></p></div>
<div><label for="sumber_dana_id" class="field-label">Sumber dana <span class="text-red-500">*</span></label><select id="sumber_dana_id" x-model="form.sumber_dana_id" class="field-input" required><option value="">Pilih sumber dana</option><template x-for="source in lookups.sumberDana" :key="source.id"><option :value="String(source.id)" x-text="source.nama_sumber"></option></template></select><p x-show="fieldErrors.sumber_dana_id" class="field-error" x-text="fieldErrors.sumber_dana_id"></p></div>
<div class="sm:col-span-2"><label for="alamat" class="field-label">Alamat <span class="text-red-500">*</span></label><input id="alamat" x-model="form.alamat" class="field-input" maxlength="255" required><p x-show="fieldErrors.alamat" class="field-error" x-text="fieldErrors.alamat"></p></div></div></section>
<section class="rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-6"><h3 class="font-semibold text-navy-900">Lokasi dan pemasangan</h3><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label for="latitude" class="field-label">Latitude</label><input id="latitude" x-model="form.latitude" class="field-input" inputmode="decimal"></div><div><label for="longitude" class="field-label">Longitude</label><input id="longitude" x-model="form.longitude" class="field-input" inputmode="decimal"></div><div><label for="tahun_anggaran" class="field-label">Tahun anggaran</label><input id="tahun_anggaran" x-model="form.tahun_anggaran" type="number" class="field-input"></div><div><label for="status" class="field-label">Status</label><select id="status" x-model="form.status" class="field-input"><option value="baik">Baik</option><option value="rusak">Rusak</option><option value="perbaikan">Perbaikan</option></select></div><div><label for="tanggal_diterima" class="field-label">Tanggal diterima</label><input id="tanggal_diterima" x-model="form.tanggal_diterima" type="date" class="field-input"></div><div><label for="tanggal_pasang" class="field-label">Tanggal pasang</label><input id="tanggal_pasang" x-model="form.tanggal_pasang" type="date" class="field-input"></div><div class="sm:col-span-2"><label for="foto" class="field-label">Foto aset <span class="font-normal text-slate-500">(maksimal 2 MB)</span></label><input id="foto" type="file" accept="image/jpeg,image/png,image/webp" @change="form.foto=$event.target.files[0]||null" class="field-input file:mr-3 file:rounded-md file:border-0 file:bg-slate-100 file:px-3 file:py-1 file:text-xs"><p x-show="currentPhoto" class="mt-2 text-xs text-slate-500">Foto saat ini: <span x-text="currentPhoto"></span></p></div><div x-show="editing" class="sm:col-span-2"><label for="keterangan_histori" class="field-label">Keterangan histori</label><input id="keterangan_histori" x-model="form.keterangan_histori" class="field-input"></div></div></section>
<div class="flex flex-col-reverse justify-end gap-3 sm:flex-row"><a href="{{ route('assets.rambu.index') }}" class="action-button">Batal</a><button type="submit" :disabled="saving" class="action-button-primary"><span x-text="saving?'Menyimpan...':(editing?'Simpan perubahan':'Simpan Rambu')">Simpan Rambu</span></button></div></form></div>
<script>function rambuForm(editing,id){return{editing,id,saving:false,error:'',currentPhoto:'',lookups:{desa:[],sumberDana:[]},fieldErrors:{},form:{desa_id:'',sumber_dana_id:'',jenis_rambu:'',alamat:'',latitude:'',longitude:'',tahun_anggaran:'',tanggal_diterima:'',tanggal_pasang:'',status:'baik',foto:null,keterangan_histori:''},async init(){if(!this.$store.auth.isAuthenticated||!['admin','operator'].includes(this.$store.auth.role)){location.href='{{ route('login') }}';return}try{const r=[window.axios.get('/api/desa'),window.axios.get('/api/sumber-dana')];if(this.editing)r.push(window.axios.get(`/api/rambu/${this.id}`));const x=await Promise.all(r);this.lookups.desa=x[0].data||[];this.lookups.sumberDana=x[1].data||[];if(this.editing)this.fill(x[2].data)}catch(e){this.error=this.msg(e)}},fill(x){this.form={...this.form,...x,desa_id:String(x.desa_id||''),sumber_dana_id:String(x.sumber_dana_id||''),foto:null};this.currentPhoto=x.foto||''},async submit(){this.saving=true;this.error='';this.fieldErrors={};const p=new FormData;Object.entries(this.form).forEach(([k,v])=>{if(v!==null&&v!=='')p.append(k,v)});if(this.editing)p.append('_method','PUT');try{await window.axios.post(this.editing?`/api/rambu/${this.id}`:'/api/rambu',p);location.href=`{{ route('assets.rambu.index') }}?success=${this.editing?'updated':'created'}`}catch(e){this.fieldErrors=e.response?.data?.errors?Object.fromEntries(Object.entries(e.response.data.errors).map(([k,v])=>[k,v[0]])):{};this.error=this.msg(e)}finally{this.saving=false}},msg(e){return e.response?.data?.message||e.message||'Terjadi kesalahan.'}}}</script>
